# .platform.app.yaml
name: todo-api
type: 'php:7.4'

dependencies:
    php: 
        composer/composer: '^2'

# Define environment variables
variables:
  env:
    APP_ENV: "prod"

# Configure deployment hooks
hooks:
  build: |
    set -e
    echo "export PLATFORM_SH_COMPOSER_VERSION=2" >> $PLATFORM_APP_DIR/.profile
    composer install --prefer-dist --no-scripts --no-progress --no-suggest --optimize-autoloader
    composer clear-cache
  deploy: |
    set -e
    bin/console cache:clear
    bin/console doctrine:schema:update --force

# Define relationships
relationships:
  database: "todo_api:mysql"

# Configure web server
web:
  locations:
    "/":
      passthru: "/index.php"