# .platform.app.yaml
name: todo-api
type: "php:7.4"

# Define environment variables
variables:
  env:
    APP_ENV: "prod"

# Configure deployment hooks
hooks:
  build: |
    composer install --prefer-dist --no-scripts --no-progress --no-suggest --optimize-autoloader
  deploy: |
    set -e
    bin/console doctrine:schema:update --force

# Define relationships
relationships:
  database: "db:mysql"

# Configure web server
web:
  locations:
    "/":
      passthru: "/index.php"

php-fpm:
  type: php:7.4
  build:
    flavor: composer
  disk: 1024
  mounts:
    "/public": "web"